# Generated by Django 3.1.2 on 2024-05-31 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0003_cafeteria_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafeteria',
            name='No',
        ),
    ]
