# Generated by Django 4.2 on 2024-06-11 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0005_add_items_c_rt_ordernow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c_rt',
            name='item_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafeteria.cafeteria'),
        ),
    ]
